"""Generate the legacy-recipe hash manifest used to backfill seed provenance.

Installs that predate the seed-content provenance system have no recorded
`installed` hash for their original dashboards, so the seed-content refresh treats
them as `user-created` and never delivers bundle improvements (colours, new
defaults) to them — even when the user never edited them (see
dev-docs/seed-content-refresh.md §10.1).

This script freezes the sha256 of every dashboard as shipped in the past releases
below. At upgrade time the re-baseline hook matches a user's *untouched* dashboard
against these hashes and backfills its provenance so the refresh can update it. A
user-edited file can never match a shipped hash, so edits stay protected.

Run from `backend/`:  python scripts/gen_legacy_recipe_hashes.py
It reads git (release tags) and writes app/seed_refresh/legacy_recipe_hashes.py.
This is a one-time transition aid — the set is frozen once these releases are past.
"""

import hashlib
import subprocess
from pathlib import Path

# The releases whose dashboards existed before the provenance system. Users on
# these versions downloaded these exact bytes, so an untouched on-disk dashboard
# will match one of these hashes. Frozen — not every tag, only pre-provenance ones.
RELEASE_TAGS = ["v0.1.2", "v0.1.3", "v0.1.4"]

DASHBOARDS_PREFIX = "backend/resources/seed_config/recipes/dashboards"
# The provenance relpath key (what refresh._decide / walk_bundle use) drops the
# `backend/resources/seed_config/` bundle-root prefix.
RELPATH_PREFIX = "recipes/dashboards"

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT = REPO_ROOT / "backend/app/seed_refresh/legacy_recipe_hashes.py"


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=REPO_ROOT, capture_output=True, text=True, check=True
    ).stdout


def collect() -> dict[str, set[str]]:
    hashes: dict[str, set[str]] = {}
    for tag in RELEASE_TAGS:
        listing = _git("ls-tree", "-r", "--name-only", tag, "--", DASHBOARDS_PREFIX)
        for path in listing.splitlines():
            if not path.endswith(".json"):
                continue
            name = path.rsplit("/", 1)[-1]
            relpath = f"{RELPATH_PREFIX}/{name}"
            content = subprocess.run(
                ["git", "cat-file", "-p", f"{tag}:{path}"],
                cwd=REPO_ROOT, capture_output=True, check=True,
            ).stdout
            variants = hashes.setdefault(relpath, set())
            variants.add(hashlib.sha256(content).hexdigest())
            # …and the same bytes with CRLF line endings, because that is what a
            # Windows user actually received. The Windows release is built from a
            # checkout with core.autocrlf enabled (the Git-for-Windows default; the
            # repo had no .gitattributes before v0.2.0), so the JSON that reached
            # their disk was CRLF while these git blobs are LF. Without the variant,
            # every Windows user's untouched dashboard fails the match, is classified
            # `user-created`, and is skipped by the refresh forever — the exact bug
            # this manifest exists to fix, just one platform over. LF-only content is
            # unaffected (the replace is a no-op on files that are already CRLF, and
            # no shipped dashboard mixed the two).
            variants.add(hashlib.sha256(content.replace(b"\n", b"\r\n")).hexdigest())
    return hashes


def render(hashes: dict[str, set[str]]) -> str:
    lines = [
        '"""GENERATED by backend/scripts/gen_legacy_recipe_hashes.py — do not edit by hand.',
        "",
        "sha256 of every pre-provenance dashboard as shipped in releases "
        + ", ".join(RELEASE_TAGS) + ",",
        "in both LF and CRLF form (the Windows builds shipped CRLF — see the generator).",
        "Used to backfill seed provenance for a user's *untouched* legacy dashboards so",
        "the seed-content refresh can update them (dev-docs/seed-content-refresh.md §10.1).",
        "A user-edited file can never match a shipped hash, so edits are never clobbered.",
        '"""',
        "",
        "LEGACY_RECIPE_HASHES: dict[str, frozenset[str]] = {",
    ]
    for relpath in sorted(hashes):
        lines.append(f"    {relpath!r}: frozenset({{")
        for h in sorted(hashes[relpath]):
            lines.append(f"        {h!r},")
        lines.append("    }),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    hashes = collect()
    OUT.write_text(render(hashes), encoding="utf-8")
    total = sum(len(v) for v in hashes.values())
    print(f"Wrote {OUT.relative_to(REPO_ROOT)}: {len(hashes)} file(s), {total} hash(es)")


if __name__ == "__main__":
    main()
