"""GENERATED by backend/scripts/gen_legacy_recipe_hashes.py — do not edit by hand.

sha256 of every pre-provenance dashboard as shipped in releases v0.1.2, v0.1.3, v0.1.4.
Used to backfill seed provenance for a user's *untouched* legacy dashboards so
the seed-content refresh can update them (dev-docs/seed-content-refresh.md §10.1).
A user-edited file can never match a shipped hash, so edits are never clobbered.
"""

LEGACY_RECIPE_HASHES: dict[str, frozenset[str]] = {
    'recipes/dashboards/financial-overview.json': frozenset({
        'cea2bac3da47b3561e448f5ddc9eaebeee0b901d7b6d6b123f34246010995d4b',
    }),
    'recipes/dashboards/month-summary.json': frozenset({
        'c7446dd802da9d360e27f20cfdce473a352283e15fc527a0938f35f161e926c8',
    }),
    'recipes/dashboards/widget-gallery.json': frozenset({
        '1d48363ffadb5263d129d3044c3af8cfd7801e6a43e9e4eb367896046ee1988f',
    }),
    'recipes/dashboards/year-summary.json': frozenset({
        'eb81631423652b5debac0d746bb918d7006bac1352a42a58375f81b691c6f1d3',
    }),
}
