"""
Centralized error code constants for APIError responses.

Import these constants instead of using raw strings to ensure consistency
between backend error raising and frontend error handling.
"""

# Validation & input errors
VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_ACCOUNT_FORMAT = "INVALID_ACCOUNT_FORMAT"
INVALID_PATH = "INVALID_PATH"
INVALID_COST = "INVALID_COST"
INVALID_PRICE = "INVALID_PRICE"
INVALID_PRICE_TYPE = "INVALID_PRICE_TYPE"
EMPTY_FILE = "EMPTY_FILE"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"

# File & path errors
FILE_NOT_FOUND = "FILE_NOT_FOUND"
FILE_PERMISSION_ERROR = "FILE_PERMISSION_ERROR"
FILE_PARSE_ERROR = "FILE_PARSE_ERROR"
DIRECTORY_NOT_FOUND = "DIRECTORY_NOT_FOUND"
NOT_A_DIRECTORY = "NOT_A_DIRECTORY"
PATH_ACCESS_ERROR = "PATH_ACCESS_ERROR"
PERMISSION_DENIED = "PERMISSION_DENIED"

# Ledger errors
LEDGER_CREATE_FAILED = "LEDGER_CREATE_FAILED"
LEDGER_INVALID = "LEDGER_INVALID"
LEDGER_NOT_READABLE = "LEDGER_NOT_READABLE"
LEDGER_PARSE_ERROR = "LEDGER_PARSE_ERROR"
LEDGER_WRITE_FAILED = "LEDGER_WRITE_FAILED"

# Account errors
ACCOUNT_ALREADY_CLOSED = "ACCOUNT_ALREADY_CLOSED"
ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS"
ACCOUNT_NOT_CLOSED = "ACCOUNT_NOT_CLOSED"
ACCOUNT_HAS_TRANSACTIONS = "ACCOUNT_HAS_TRANSACTIONS"
ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND"
ACCOUNT_UPDATE_ERROR = "ACCOUNT_UPDATE_ERROR"

# Transaction errors
TRANSACTION_CREATION_FAILED = "TRANSACTION_CREATION_FAILED"
TRANSACTION_INVALID = "TRANSACTION_INVALID"
TRANSACTION_VALIDATION_FAILED = "TRANSACTION_VALIDATION_FAILED"
ALL_TRANSACTIONS_INVALID = "ALL_TRANSACTIONS_INVALID"
NO_TRANSACTION_IDS = "NO_TRANSACTION_IDS"
NO_TRANSACTIONS = "NO_TRANSACTIONS"
NO_TRANSACTIONS_FOUND = "NO_TRANSACTIONS_FOUND"
TRANSACTIONS_NOT_FOUND = "TRANSACTIONS_NOT_FOUND"

# Resource errors
RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
DIRECTIVE_NOT_FOUND = "DIRECTIVE_NOT_FOUND"

# Query errors
QUERY_EXECUTION_ERROR = "QUERY_EXECUTION_ERROR"
QUERY_SYNTAX_ERROR = "QUERY_SYNTAX_ERROR"
QUERY_TIMEOUT = "QUERY_TIMEOUT"
SCHEMA_NOT_FOUND = "SCHEMA_NOT_FOUND"
TABLE_NOT_FOUND = "TABLE_NOT_FOUND"
DATABASE_NOT_FOUND = "DATABASE_NOT_FOUND"

# Config errors
CONFIG_ERROR = "CONFIG_ERROR"
CONFIG_SAVE_ERROR = "CONFIG_SAVE_ERROR"
YAML_PARSE_ERROR = "YAML_PARSE_ERROR"

# AI/LLM errors
AI_CATEGORIZE_FAILED = "AI_CATEGORIZE_FAILED"
AI_NOT_CONFIGURED = "AI_NOT_CONFIGURED"
AI_PARSE_ERROR = "AI_PARSE_ERROR"
AI_REQUEST_FAILED = "AI_REQUEST_FAILED"
LLM_CALL_FAILED = "LLM_CALL_FAILED"
LLM_EMPTY_RESPONSE = "LLM_EMPTY_RESPONSE"
LLM_INVALID_FORMAT = "LLM_INVALID_FORMAT"
LLM_INVALID_JSON = "LLM_INVALID_JSON"
LLM_NOT_CONFIGURED = "LLM_NOT_CONFIGURED"
CLIENT_DISCONNECTED = "CLIENT_DISCONNECTED"

# Import/export errors
ENGINE_NOT_SUPPORTED = "ENGINE_NOT_SUPPORTED"
INVALID_ENGINE = "INVALID_ENGINE"
MISSING_DEPENDENCY = "MISSING_DEPENDENCY"
PDF_NATIVE_NOT_SUPPORTED = "PDF_NATIVE_NOT_SUPPORTED"
PDF_NO_TEXT = "PDF_NO_TEXT"

# CRUD operation errors
DELETE_FAILED = "DELETE_FAILED"
UPDATE_FAILED = "UPDATE_FAILED"

# Auth errors (hosted mode)
AUTH_REQUIRED = "AUTH_REQUIRED"
INVALID_USER_ID = "INVALID_USER_ID"

# General errors
HTTP_EXCEPTION = "HTTP_EXCEPTION"
NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
UNKNOWN_SERVER_ERROR = "UNKNOWN_SERVER_ERROR"
MEMORY_PRESSURE = "MEMORY_PRESSURE"
